### ISSUE TITLE
How to change the SSH/telnet/FTP login password?

### ISSUE THREAD

**Issue by CrescendoFang** [shadow-1/yi-hack-v3#108]
How to change the SSH/telnet/FTP login password?

Or maybe put a login password to access the web interface for more security?

**Comment by shadow-1** [comment]
@CrescendoFang 
Changing the SSH/Telnet/FTP password is actually quite simple. You have to login to the camera via SSH or Telnet. Once at the console, enter the following command: `passwd` and follow the prompts.

Changing the password in this way will change the password for SSH, Telnet and FTP.

I have resisted the urge to create a login page for the web interface at this stage. In my opinion, it is not a priority task. My main concern is that when you have a login page, I suspect it will be best to change the web interface to utilise HTTPS rather than HTTP (like it is at the moment). Utilising HTTPS will require additional libraries being made available on the camera. In addition I will have to deal with security certificates. Due to the unknown free space required for the other features I plan to implement, I think I will hold off developing a login page for the web interface, at least until much later on.
